project_id = "sbwnrousokvilaokkeno"

[functions.generate-recommendations]
verify_jwt = false

[functions.generate-alerts]
verify_jwt = false

[functions.calculate-daily-consumption]
verify_jwt = false

[functions.analyze-appliance]
verify_jwt = true

[functions.volti-chat]
verify_jwt = false
